name: petshop-dash
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
        image: darshandock:latest
        working_dir: /var/www/
        restart: unless-stopped

    mysql:
        image: mysql:8
        ports:
            - "33006:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
        driver: "local"
